### ISSUE TITLE
Containerize and add installation & running guidelines 

### ISSUE THREAD

**Issue by tamanna-sb** [afrin110203/LogAnomaliesDetectionDL#8]
1. Containerize the program with dataset to give anyone the choice of running the application  by cloning the docker; without installing any component
2. Add installation and running guidelines in README.md

**Comment by RubyaAfrin** [comment]
Right now I am learning "How to containerize the program with docker". After completing the documentation, I'll add to the README.md file with installation guidelines.

**Comment by tamanna-sb** [comment]
Thanks for the update. I understand, it will take some time. However, I think it is better to keep the issue open. You should close it after you are done with the procedure and link your pull request with the issue.

**Comment by RubyaAfrin** [comment]
Ok. I will reopen this.

**Comment by RubyaAfrin** [comment]
I have containerized the project with details guidelines in [reademe.md ](https://github.com/afrin110203/LogAnomaliesDetectionDL/blob/main/README.md)file. Please install the [docker desktop app ](https://www.docker.com/get-started/)and follow the instructions to run the project on your local machine.

*Note: So far, I have completed parsing the log files and counting the event types. Anomaly detection is yet to be solved.
