### ISSUE TITLE
Detailed instructions on how to run locally with parameters 

### ISSUE THREAD

**Issue by nevyn-pablo** [afrin110203/LogAnomaliesDetectionDL#9]

**Comment by RubyaAfrin** [comment]
You need to fork my repo and install Python 2.7

Still I need to modify some of my functions for different datasets.
I will provide details documentation after completing my coding.

**Comment by RubyaAfrin** [comment]
I have added the detail description for running my project in [reademe.md ](https://github.com/afrin110203/LogAnomaliesDetectionDL/blob/main/README.md) file. Please install the [docker desktop app ](https://www.docker.com/get-started/) and run the project.

*Note: So far, I have completed parsing the log files and counting the event types. Anomaly detection is yet to be solved.
